name: Settings
  
targets:
  Settings:
    type: framework
    platform: iOS

    sources:
      - path: Settings
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.dias.settings
    dependencies:
      - framework: SettingsInterface.framework
        implicit: true
      - framework: RouterServiceInterface.framework
        implicit: true
      - framework: HTTPClientInterface.framework
        implicit: true
      - framework: FeatureFlagInterface.framework
        implicit: true

schemes:
  Settings:
    build:
      targets:
        Settings: all
