name: HelpInterface

options:
  deploymentTarget:
    iOS: 13.0

targets:
  HelpInterface:
    type: framework
    platform: iOS

    sources:
      - path: HelpInterface
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.dias.help.interface
    dependencies:
      - framework: RouterServiceInterface.framework
        implicit: true

schemes:
  HelpInterface:
    build:
      targets:
        HelpInterface: all
