name: Home

options:
  deploymentTarget:
    iOS: 13.0

targets:
  Home:
    type: framework
    platform: iOS

    sources:
      - path: Home
        excludes:
          - "**/*.md"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.dias.home
    dependencies:
      - framework: RouterServiceInterface.framework
        implicit: true
      - framework: HTTPClientInterface.framework
        implicit: true
      - framework: FeatureFlagInterface.framework
        implicit: true
      - framework: HomeInterface.framework
        implicit: true

    preBuildScripts:
      - script: 'swiftlint --config ../../.swiftlint.yml'
        name: SwiftLint


  HomeTests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - path: HomeTests

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.dias.home.tests

    dependencies:
      - target: Home
      - target: HomeSample

  HomeSample:
    type: application
    platform: iOS
    sources: [HomeSample]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: br.com.dias.home.sample

    dependencies:
      - target: Home

schemes:
  Home:
    build:
      targets:
        Home: all
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: HomeTests
          parallelizable: false
          randomExecutionOrder: true
